src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Designation;

    #[ORM\OneToMany(mappedBy: 'entreprise', targetEntity: PFE::class)]
    private $ListePFE;

    public function __construct()
    {
        $this->ListePFE = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->Designation;
    }

    public function setDesignation(?string $Designation): self
    {
        $this->Designation = $Designation;

        return $this;
    }
    public function __toString()
    {
        return $this->Designation;
    }
    /**
     * @return Collection<int, PFE>
     */
    public function getListePFE(): Collection
    {
        return $this->ListePFE;
    }

    public function addListePFE(PFE $listePFE): self
    {
        if (!$this->ListePFE->contains($listePFE)) {
            $this->ListePFE[] = $listePFE;
            $listePFE->setEntreprise($this);
        }

        return $this;
    }

    public function removeListePFE(PFE $listePFE): self
    {
        if ($this->ListePFE->removeElement($listePFE)) {
            // set the owning side to null (unless already changed)
            if ($listePFE->getEntreprise() === $this) {
                $listePFE->setEntreprise(null);
            }
        }

        return $this;
    }
}

src/Entity/PFE.php
<?php

namespace App\Entity;

use App\Repository\PFERepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PFERepository::class)]
class PFE
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $title;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $NomStudent;

    #[ORM\ManyToOne(targetEntity: Entreprise::class, inversedBy: 'ListePFE')]
    private $entreprise;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getNomStudent(): ?string
    {
        return $this->NomStudent;
    }

    public function setNomStudent(?string $NomStudent): self
    {
        $this->NomStudent = $NomStudent;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }
}

src/Form/PFEType.php
<?php

namespace App\Form;

use App\Entity\PFE;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PFEType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('NomStudent')
            ->add('entreprise')
            ->add("Subimit",SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PFE::class,
        ]);
    }
}

src/Controller/AddPFEController.php
<?php

namespace App\Controller;


use App\Entity\PFE;
use App\Form\PFEType;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AddPFEController extends AbstractController
{
    #[Route('/add/', name: 'app_add_p_f_e')]
    public function index(ManagerRegistry $doctrine, Request $request): Response {
        $entityManager = $doctrine->getManager();

        $pfe = new PFE();
        $form = $this->createForm(PFEType::class, $pfe);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $entityManager->persist($pfe);
            $entityManager->flush();
            return $this->render('pfe.info.html.twig',['pfe' => $pfe]);
        } else {
            return $this->render('add_pfe/index.html.twig', [
                'form' => $form->createView()
            ]);
        }

    }


}

src/Controller/AfficheController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Entity\PFE;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Config\Framework\WebLinkConfig;

class AfficheController extends AbstractController
{

    #[Route('/stats', name: 'app_stats')]
    public function index(ManagerRegistry $doctrine,): Response {
        $repo = $doctrine->getRepository(PFE::class);
        $PFEparEntreprise = $repo->countPFE();

        return $this->render('stats/index.html.twig', [
            'PFEparEntreprise' => $PFEparEntreprise
        ]);
    }
    #[Route('/all', name: 'app_all')]
    public function afficheAll(ManagerRegistry $doctrine,): Response {
        $repo = $doctrine->getRepository(PFE::class);
        $allPFE = $repo->findAll();

        return $this->render('all/index.html.twig', [
            'listePFE' => $allPFE
        ]);
    }



}

templates/add_pfe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une PFE{% endblock %}

{% block PageTitle %} Remplir le formulaire pour ajouter une PFE{% endblock %}

{% block body %}
    {{ form(form) }}
{% endblock %}

templates/all/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des PFEs{% endblock %}
{% block PageTitle %}
    Liste des PFEs
{% endblock %}
{% block body %}
    <div class="row">
        {% for PFE in listePFE %}
            <div class="card text-white bg-{% if(loop.index is odd) %}primary{% else %}success{% endif %} m-2 col-4"
                 style="max-width: 18rem;">
                <div class="card-header">{{ PFE.title }}</div>
                <div class="card-body">
                    <h5 class="card-title"> Etudiant : {{ PFE.nomStudent }}</h5>
                    <p class="card-text">Entreprise : {{ PFE.entreprise }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('node_modules/bootstrap/dist/css/bootstrap.css') }}">
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="alert alert-info mt-4 mb-4" role="alert">
        {% block PageTitle %}
            Placeholder
        {% endblock %}
    </div>
    {% block body %}

    {% endblock %}
</div>

{% block javascripts %}
    <script src="dist/{{ asset('node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="dist/{{ asset('node_modules/@popperjs/core/dist/umd/popper.min.js') }}"></script>
{% endblock %}
</body>
</html>

templates/pfe.info.html.twig
{% extends 'base.html.twig' %}
{% block title %} Ajout avec succés! {% endblock %}

{% block PageTitle %} Le PFE a été ajouté avec succés{% endblock %}

{% block body %}
    <h1> Titre du PFE : {{ pfe.title }}</h1>
    <h2>Nom du l'étudiant : {{ pfe.nomStudent }}</h2>
    <h2>Entreprise: {{ pfe.entreprise }}</h2>
{% endblock %}

templates/stats/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une PFE{% endblock %}
{% block PageTitle %}
    Nombres de PFE par entreprises
{% endblock %}
{% block body %}
    <div class="row">
    {% for entreprise in PFEparEntreprise %}
        <div class="card text-white bg-{%if(loop.index is odd)%}primary{% else %}success{% endif %} m-2 col-3" style="max-width: 18rem;">
            <div class="card-header">{{ entreprise['Designation'] }}</div>
            <div class="card-body">
                <h5 class="card-title">{{ entreprise[1] }} Pfe(s)</h5>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}